### ISSUE TITLE
Acrylics glass

### ISSUE THREAD

**Issue by sallar** [2dom/PixelTimes#1]
Hi, 

Cool project :) I'm trying to build a similar thing since last year. I have one issue though, can't find a place to buy the same Acrylic glass that you have used... Could you point me in the right direction?

Thanks!

**Comment by 2dom** [comment]
Hi,

thanks! I just got it from the guy that owns the laser cutter - no idea where he sources it from. However, ebay sells lots of acrylics in all forms and colors. 

Tobias also had a good idea (check http://www.instructables.com/id/Tetris-Time-on-a-P10-RGB-Matrix-With-ESP8266/). He used foil on milky white acrylics instead of gray acrylics. (I think he used mirror foil but Aliexpress also has them in black (https://www.aliexpress.com/item/0-5-3m-Light-Gray-uv-insulation-Car-Window-Tint-Film-VLT-45-2-ply-Solar/32362470338.html?spm=a2g0s.9042311.0.0.0QM16B)

Cheers Dom

**Comment by sallar** [comment]
Thank you for your help :)
